---
# Install packages from AUR using yay
# Requires: aur_builder user and yay to be installed first

- name: Install AUR packages using yay
  kewlfft.aur.aur:
    name: "{{ aur_packages }}"
    use: yay
    state: present
  become: true
  become_user: aur_builder
  when: aur_packages is defined and aur_packages | length > 0
