---
# User and group management

- name: Ensure wheel group exists
  become: true
  ansible.builtin.group:
    name: wheel
    state: present

- name: Grant wheel group sudo access
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/10-wheel
    line: '%wheel ALL=(ALL:ALL) ALL'
    create: true
    mode: '0440'
    validate: 'visudo -cf %s'

